# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Heavily borrowed from SuperTuxKart's travis.yml.
#
# SuperTuxKart's travis.yml file can be found here:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# License: https://github.com/supertuxkart/stk-code/blob/master/COPYING
#

language: cpp

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

sudo: false

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "eVEyzIVjDlB16EPkXmj74tyF9pgX34kpgvBUMXJJ+hduuPwaGC6vl8T164fNQUIua2Z2/PqxmTLJRR3n5Bbkdf859NdX+4JUzc3SoFEKlgcLMYnOQeuimUAiMKxe4vmC4sub5LZVFsp9ORzVYkXgiMBnxiD5GuYxvZPy1lCaH9E="
    - CMAKE_VERSION=3.3.0 SDL2_VERSION=2.0.3 SDL2IMAGE_VERSION=2.0.0
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"
 
before_install:

  # CMake
  - wget http://www.cmake.org/files/v3.3/cmake-$CMAKE_VERSION.tar.gz -O - | tar xz
  - (cd cmake-$CMAKE_VERSION && cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/cmake . && make -j3 && make install)

  # SDL dependencies
  - wget http://libsdl.org/release/SDL2-$SDL2_VERSION.tar.gz -O - | tar xz
  - (cd SDL2-$SDL2_VERSION && ./configure --prefix=$HOME/lib && make -j3 && make install)
  - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-$SDL2IMAGE_VERSION.tar.gz -O - | tar xz
  - (cd SDL2_image-$SDL2IMAGE_VERSION && ./configure --prefix=$HOME/lib && make -j3 && make install)

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON
  - make VERBOSE=1 -j3

addons:
  coverity_scan:
    project:
      name: "SuperTux/supertux"
      description: "Build submitted via Travis CI"
    notification_email: supertux-commit@lists.lethargik.org
    build_command_prepend: "cmake . && make clean"
    build_command:   "make -j 3"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - build-essential
    # Current gcc that supports C++ 11 features
    - g++4.9
    - gcc-4.9
    - libogg-dev
    - libvorbis-dev
    - libphysfs-dev
    - libglew-dev
    - libopenal-dev
    - libboost-all-dev


notifications:
  email:
    - supertux-commit@lists.lethargik.org
